all:
	rnn_prof irt assistments skill_builder_data_big.txt --onepo \
	--drop-duplicates --no-remove-skill-nans --num-folds 5 \
	--item-id-col problem_id --concept-id-col single 

assist09:
	rnn_prof irt assist09 skill_builder_data_big.txt --onepo \
	--drop-duplicates --no-remove-skill-nans --num-folds 5 \
	--item-id-col problem_id --concept-id-col single
